services:
  - type: web
    name: telegram-checklist-bot
    env: python
    plan: free
    region: frankfurt
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        value: 8405014883:AAFqXTQcXuLYmurfBucI_4ml8vzHtkahtAo
